name: Auto Post Reels on Schedule (IST)

on:
  # Agar aap chahein to testing ke liye isse on rakh sakte hain.
  # Code mein badlav karke push karne par yeh apne aap chalega.
  push:
    branches:
      - main
  
  # Yeh action ko schedule par chalayega
  schedule:
    # Zaroori Note: GitHub ka time UTC mein hota hai. IST, UTC se 5 ghante 30 minute aage hai.
    # Isliye hum time ko UTC mein convert karke likhenge.

    # Subha 9:00 AM IST (hota hai 3:30 UTC)
    - cron: '30 3 * * *'
    
    # Dopehar 1:00 PM IST (hota hai 7:30 UTC)
    - cron: '30 7 * * *'
    
    # Shaam 6:00 PM IST (hota hai 12:30 UTC)
    - cron: '30 12 * * *'
    
    # Raat 9:00 PM IST (hota hai 15:30 UTC)
    - cron: '30 15 * * *'
    
  # Workflow ko manually chalaane ke liye
  workflow_dispatch:

# === YEH BLOCK ZAROORI HAI ===
# Yeh action ko repository mein likhne (write) ki permission deta hai
permissions:
  contents: write

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Code ko runner machine par download karega
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Python ka environment set up karega
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: FFMPEG install karega (moviepy ke liye zaroori hai)
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # Step 4: Python ki zaroori libraries install karega
      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt
      
      # Step 5: Python script ko chalayega
      - name: Run Python script
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          INSTAGRAM_USER_ID: ${{ secrets.INSTAGRAM_USER_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: python auto_poster.py
        
      # Step 6: last_uploaded.txt file mein hue badlav ko wapas repository mein save karega
      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add last_uploaded.txt
          # Sirf tabhi commit karega jab file mein koi badlav hua ho
          git diff --staged --quiet || git commit -m "Update last uploaded part number"
          git push
