name: Auto Post Reels on Schedule (IST)

on:
  push:
    branches:
      - main
  
  schedule:
    # Schedule (Indian Time)
    - cron: '30 3 * * *'  # Subha 9:00 AM IST
    - cron: '30 7 * * *'  # Dopehar 1:00 PM IST
    - cron: '30 12 * * *' # Shaam 6:00 PM IST
    - cron: '30 15 * * *' # Raat 9:00 PM IST
    
  workflow_dispatch:

# Action ko repository mein likhne (write) ki permission deta hai
permissions:
  contents: write

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python with dependency caching
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt
      
      - name: Run Python script
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          INSTAGRAM_USER_ID: ${{ secrets.INSTAGRAM_USER_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: python auto_poster.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          # === YAHAN FIX KIYA GAYA HAI ===
          # Filename ko 'last_uploaded.txt' se 'posted_parts.txt' kar diya hai
          git add posted_parts.txt
          git diff --staged --quiet || git commit -m "Update posted parts list"
          git push
